#!/bin/bash
set -ex
git_url="$1"
platform="$2"
name="$3"
result_file="$4"
source /srv/passenger_autobuilder/app/pbuilder-environment
export CCACHE_DIR="/srv/passenger_autobuilder/ccache/psg_autobuilder_chroot/$platform"
repo_dir="/srv/passenger_autobuilder/repos/$name"
mkdir -p "$CCACHE_DIR"
exec ~/.rvm/bin/rvm-exec ruby-2.0.0 ruby /srv/passenger_autobuilder/app/autobuild-standalone \
	--git-url "$git_url" \
	--repo-dir "$repo_dir" \
	--output-dir "/srv/passenger_autobuilder/output/$name" \
	--work-tag "$platform" \
	--result-file "$result_file"
