#!/bin/bash
set -e

reset='\x1B[0m'
bold='\x1B[1m'
red='\x1B[31m'
green='\x1B[32m'
yellow='\x1B[33m'

function status()
{
	echo -e "${yellow}# ${@}${reset}"
}

function success()
{
	echo -e "${green}${@}${reset}"
}

function warn()
{
	echo -e "${yellow}${@}${reset}"
}

function error()
{
	echo -e "${bold}${@}${reset}"
}

git_url="$1"
name="$2"
only_one="$3"

if [[ "$git_url" = "" || "$name" = "" ]]; then
	echo "Usage: ./autobuild-with-pbuilder GIT_URL NAME [--only-one]"
	exit 1
fi

function perform()
{
	local base_tgz
	local arch
	local platform
	base_tgz="$1"
	arch="$2"
	platform="$3"

	local maybe_linux32
	if [[ $arch == i386 ]]; then
		maybe_linux32=linux32
	else
		maybe_linux32=
	fi

	status "Performing build: $platform"
	$maybe_linux32 pbuilder execute \
		--basetgz "$base_tgz" \
		--bindmounts "/srv/passenger_autobuilder" -- \
		"/srv/passenger_autobuilder/autobuild-bootstrap-in-pbuilder" \
		"$git_url" "$platform" "$name"
}

perform lucid-amd64.tgz amd64 ubuntu-10.04-x86_64
if [[ "$only_one" != "" ]]; then exit; fi
perform lucid-i386.tgz i386 ubuntu-10.04-x86
