#!/bin/bash
set -ex
git_url="$1"
platform="$2"
name="$3"
source /srv/passenger_autobuilder/pbuilder-environment
export CCACHE_DIR="/srv/passenger_autobuilder/ccache/$platform"
repo_dir="/srv/passenger_autobuilder/repo/$name"
mkdir -p "$CCACHE_DIR"
mkdir -p "`dirname \"$repo_dir\"`"
exec ruby1.9 /srv/passenger_autobuilder/autobuild-standalone \
	--git-url "$git_url" \
	--repo-dir "$repo_dir" \
	--output-dir "/srv/passenger_autobuilder/output/$name/$platform"
