#!/bin/bash
set -ex

PASSENGER_AUTOBUILDER_APP_DIR="$1"
name="$2"
platform="$3"
shift
shift
shift

source $PASSENGER_AUTOBUILDER_APP_DIR/pbuilder-environment
export CCACHE_DIR="/srv/passenger_autobuilder/ccache/psg_autobuilder_chroot/$platform/$name"
export GIT_SSH="$PASSENGER_AUTOBUILDER_APP_DIR/git-ssh"

umask u=rwx,g=rwx,o=rx
repo_dir="/srv/passenger_autobuilder/repos/$name"
mkdir -p "$CCACHE_DIR"

gpg --import $PASSENGER_AUTOBUILDER_APP_DIR/*.key
gpg --import-ownertrust <<EOF
# List of assigned trustvalues, created Mon 01 Jul 2013 07:19:06 AM CEST
# (Use "gpg --import-ownertrust" to restore them)
573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62:6:
A09CD539B8BB8CBE96E82BDFABD4D3B3F5806B4D:6:
4C2C85E705DC730833990C38A9376139A524C53E:6:
B0F4253373F8F6F510D42178520A9993A1C052F8:6:
EOF

exec ~/.rvm/bin/rvm-exec ruby-2.2.3 ruby $PASSENGER_AUTOBUILDER_APP_DIR/autobuild-standalone \
	--repo-dir "$repo_dir" \
	--output-dir "/srv/passenger_autobuilder/output/$name" \
	"$@"
