#!/bin/bash
set -e

function apt_get_install()
{
	apt-get install -y --no-recommends "$@"
}

echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/02apt-speedup

apt_get_install build-essential apache2-mpm-worker apache2-threaded-dev libcurl4-openssl-dev
apt_get_install ruby1.8 ruby1.8-dev rubygems ruby1.9 ruby1.9-dev rake
