#!/bin/bash
set -ev

environment="$1"
platform="$2"
eval "$environment"
export CCACHE_DIR="/srv/passenger_autobuilder/ccache/$platform"
mkdir -p "$CCACHE_DIR"
cd /tmp

function apt_get_install()
{
	apt-get install -y --no-install-recommends "$@"
}

apt_version=`apt-get --version | head -n 1 | awk '{print $2}'`
[[ "$apt_version" =~ ^([0-9]+)\.([0-9]+) ]]
if [[ ${BASH_REMATCH[1]} > 0 ]] || [[ ${BASH_REMATCH[1]} == 0 && ${BASH_REMATCH[2]} > 7 ]]; then
	echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/02apt-speedup
fi

addgroup --gid 2456 passenger_autobuilder
adduser --uid 2456 --gid 2456 --disabled-password --gecos "Passenger Autobuilder" passenger_autobuilder

apt-get update
apt-get upgrade -y
apt_get_install python-software-properties
add-apt-repository ppa:phusion.nl/misc
apt-get update

apt_get_install build-essential ccache wget source-highlight lsb-release ssh sudo
apt_get_install apache2-mpm-worker apache2-threaded-dev libssl-dev
apt_get_install ruby ruby1.8 ruby1.8-dev rubygems ruby1.9 ruby1.9-dev rake mizuho

distro_version=`lsb_release -r | awk '{print $2}'`
if [[ $distro_version = 10.04 ]]; then
	apt_get_install git-core
else
	apt_get_install git
fi

gem install bluecloth --no-rdoc --no-ri

# Compile a static OpenSSL library.
if [[ ! -e /usr/local/override/bin/openssl ]]; then
	wget http://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
	tar xzvf openssl-$OPENSSL_VERSION.tar.gz
	rm openssl-$OPENSSL_VERSION.tar.gz
	cd openssl-$OPENSSL_VERSION
	./config --prefix=/usr/local/override --openssldir=/usr/local/override/openssl threads zlib no-shared no-sse2
	make
	make install_sw
	cd ..
	rm -rf openssl-$OPENSSL_VERSION
fi

# Compile a minimalist libcurl with almost no dependencies.
if [[ ! -e /usr/local/override/bin/curl ]]; then
	wget http://curl.haxx.se/download/curl-$CURL_VERSION.tar.bz2
	tar xjvf curl-$CURL_VERSION.tar.bz2
	rm curl-$CURL_VERSION.tar.bz2
	cd curl-$CURL_VERSION
	./configure --prefix=/usr/local/override --disable-shared --disable-manual --disable-ldap --disable-ldaps \
		--disable-rtsp --disable-dict --disable-ftp --disable-ftps --disable-gopher --disable-imap \
		--disable-imaps --disable-pop3 --disable-pop3s --without-librtmp --disable-smtp --disable-smtps \
		--disable-telnet --disable-tftp --without-libmetalink --without-libidn
	make install
	cd ..
	rm -rf curl-$CURL_VERSION
fi
