#!/bin/bash
reset='\x1B[0m'
bold='\x1B[1m'
red='\x1B[31m'
green='\x1B[32m'
yellow='\x1B[33m'

function status()
{
	echo -e "${yellow}# ${@}${reset}"
}

function success()
{
	echo -e "${green}${@}${reset}"
}

function warn()
{
	echo -e "${yellow}${@}${reset}"
}

function error()
{
	echo -e "${bold}${@}${reset}"
}

PASSENGER_AUTOBUILDER_ROOT=/srv/passenger_autobuilder
PASSENGER_AUTOBUILDER_APP_DIR=${PASSENGER_AUTOBUILDER_APP_DIR:-"$PASSENGER_AUTOBUILDER_ROOT/app"}
PASSENGER_AUTOBUILDER_CCACHE_DIR="$PASSENGER_AUTOBUILDER_ROOT/ccache"
PASSENGER_AUTOBUILDER_REPOS_DIR="$PASSENGER_AUTOBUILDER_ROOT/repos"
PASSENGER_AUTOBUILDER_OUTPUT_DIR="$PASSENGER_AUTOBUILDER_ROOT/output"
PASSENGER_AUTOBUILDER_IMAGES_DIR="$PASSENGER_AUTOBUILDER_ROOT/images"
PASSENGER_AUTOBUILDER_RUN_DIR="$PASSENGER_AUTOBUILDER_ROOT/run"
PASSENGER_AUTOBUILDER_CONFIG_DIR="$PASSENGER_AUTOBUILDER_ROOT/config"

cd "$PASSENGER_AUTOBUILDER_APP_DIR"
