#!/bin/bash
PASSENGER_AUTOBUILDER_APP=`dirname "$0"`
PASSENGER_AUTOBUILDER_APP=`cd "$PASSENGER_AUTOBUILDER_APP"; pwd`
source "$PASSENGER_AUTOBUILDER_APP/library"

base_tgz="$1"
shift
if [[ "$base_tgz" = "" ]]; then
	echo "Usage: ./login-pbuilder <BASE_TGZ> [--save-after-login]"
	exit 1
fi
if [[ "$base_tgz" =~ i386 ]]; then
	maybe_linux32=linux32
else
	maybe_linux32=
fi
exec $maybe_linux32 sudo pbuilder login "$@" \
	--bindmounts "$PASSENGER_AUTOBUILDER_ROOT" \
	--basetgz "$base_tgz"
