#!/bin/bash
set -e

reset='\x1B[0m'
bold='\x1B[1m'
red='\x1B[31m'
green='\x1B[32m'
yellow='\x1B[33m'

function status()
{
	echo -e "${yellow}# ${@}${reset}"
}

function success()
{
	echo -e "${green}${@}${reset}"
}

function warn()
{
	echo -e "${yellow}${@}${reset}"
}

function error()
{
	echo -e "${bold}${@}${reset}"
}

function init_base_tgz()
{
	local base_tgz
	local distro
	local arch
	local maybe_linux32
	base_tgz="$1"
	distro="$2"
	arch="$3"
	maybe_linux32="$4"

	status "Creating $base_tgz..."
	$maybe_linux32 pbuilder create --basetgz "$base_tgz.initiating" \
		--distribution $distro --architecture $arch \
		--override-config --components "main universe"
	mv "$base_tgz.initiating" "$base_tgz.initial"
}

function modify_base_tgz()
{
	local base_tgz
	local platform
	local maybe_linux32
	base_tgz="$1"
	platform="$2"
	maybe_linux32="$3"

	status "Installing necessary software in $base_tgz..."
	$maybe_linux32 pbuilder execute \
		--basetgz "$base_tgz.initial" \
		--save-after-login \
		--bindmounts /srv/passenger_autobuilder \
		base-tgz-setup \
		"`cat pbuilder-environment`" \
		"$platform"
	mv "$base_tgz.initial" "$base_tgz"
}

function create_base_tgz()
{
	local base_tgz
	local distro
	local arch
	local platform
	local maybe_linux32

	base_tgz="$1"
	distro="$2"
	arch="$3"
	platform="$4"
	if [[ $arch == i386 ]]; then
		maybe_linux32=linux32
	else
		maybe_linux32=
	fi

	if [[ -f "$base_tgz" ]]; then
		success "$base_tgz already exists"
	elif [[ -f "$base_tgz.initial" ]]; then
		modify_base_tgz "$base_tgz" "$platform" "$maybe_linux32"
	else
		init_base_tgz "$base_tgz" "$distro" "$arch" "$maybe_linux32"
		modify_base_tgz "$base_tgz" "$platform" "$maybe_linux32"
	fi
}

create_base_tgz lucid-amd64.tgz lucid amd64 ubuntu-10.04-x86_64
create_base_tgz lucid-i386.tgz lucid i386 ubuntu-10.04-x86
