#!/bin/bash
set -e

dir=`dirname "$0"`
cd "$dir"
if "`pwd`" != /srv/passenger_autobuilder/app; then
	echo "passenger_autobuilder MUST be located in /srv/passenger_autobuilder/app."
	exit 1
fi

function create_user()
{
	local name="$1"
	local full_name="$2"
	local id="$3"
	create_group $name $id
	if ! grep -q "^$name:" /etc/passwd; then
		sudo adduser --uid $id --gid $id --disabled-password --gecos "$full_name" $name
	fi
	sudo usermod -L $name
}

function create_group()
{
	local name="$1"
	local id="$2"
	if ! grep -q "^$name:" /etc/group >/dev/null; then
		sudo addgroup --gid $id $name
	fi
}

set -x
cd /srv/passenger_autobuilder
create_user psg_autobuilder "Passenger Autobuilder" 2456
create_user psg_autobuilder_chroot "Passenger Autobuilder Chroot" 2457
create_user psg_autobuilder_run "Passenger Autobuilder Run" 2458

create_group passenger_ci 2450
sudo usermod -a -G passenger_ci psg_autobuilder_run
sudo mkdir -p /var/cache/passenger_ci
sudo touch /var/cache/passenger_ci/lock
sudo chown -R root:passenger_ci /var/cache/passenger_ci
sudo chmod 770 /var/cache/passenger_ci
sudo chmod 660 /var/cache/passenger_ci/lock

umask u=rwx,g=rwx,o=rx
sudo chown root: .
sudo chmod g-w,o-w .

sudo apt-get install -y ubuntu-dev-tools pbuilder sudo s3cmd

sudo mkdir -p output repos images run
sudo mkdir -p ccache ccache/pbuilder ccache/psg_autobuilder_chroot

sudo chown -R psg_autobuilder:psg_autobuilder app
sudo chown -R psg_autobuilder_chroot:psg_autobuilder_chroot repos ccache/psg_autobuilder_chroot
sudo chown -R psg_autobuilder_chroot:psg_autobuilder_run output
sudo chown -R psg_autobuilder_run:psg_autobuilder_chroot run

sudo chmod o-rx ccache/pbuilder ccache/psg_autobuilder_chroot repos
sudo chmod 755 app
sudo chmod u=rwx,g=rwxs,o=x output
sudo chmod 770 run

sudo touch run/sync_to_s3.lock
sudo chown psg_autobuilder_run:psg_autobuilder_chroot run/sync_to_s3.lock
sudo chmod u=rwx,g=rwx,o= run/sync_to_s3.lock

sudo cp app/sudoers.conf /etc/sudoers.d/passenger_autobuilder
sudo chmod 440 /etc/sudoers.d/passenger_autobuilder

if [[ ! -f app/signing_configuration ]]; then
	sudo cp app/signing_configuration.example app/signing_configuration
	sudo nano app/signing_configuration
fi
sudo chown psg_autobuilder_run:psg_autobuilder_run app/signing_configuration
sudo chmod 600 app/signing_configuration
