#!/bin/bash
set -e

PASSENGER_AUTOBUILDER_APP=`dirname "$0"`
PASSENGER_AUTOBUILDER_APP=`cd "$PASSENGER_AUTOBUILDER_APP"; pwd`
source "$PASSENGER_AUTOBUILDER_APP/library"
source "$PASSENGER_AUTOBUILDER_APP/s3_configuration"

if [[ "$S3_TARGET" = "" ]]; then
	echo "S3_TARGET not set in s3_configuration. Not syncing to Amazon S3."
	exit
fi

function cleanup()
{
	local pids=`jobs -p`
	if [[ "$pids" != "" ]]; then
		kill $pids
	fi
}

trap cleanup EXIT

for DIR in $PASSENGER_AUTOBUILDER_OUTPUT_DIR/*; do
	name=`basename "$DIR"`
	status "Syncing $DIR to Amazon S3..."
	chpst -l $PASSENGER_AUTOBUILDER_RUN_DIR/sync_to_s3.lock \
		s3cmd sync --follow-symlinks --delete-removed $DIR/by_release/ $S3_TARGET/$name/by_release/
done
