#!/bin/bash
set -e

SELFDIR=`dirname "$0"`
SELFDIR=`cd "$SELFDIR"; pwd`
source "$SELFDIR/library"
source "$PASSENGER_AUTOBUILDER_CONFIG_DIR/s3"

if [[ "$S3_TARGET" = "" ]]; then
	echo "S3_TARGET not set in $PASSENGER_AUTOBUILDER_CONFIG_DIR/s3. Not syncing to Amazon S3."
	exit
fi

function cleanup()
{
	local pids=`jobs -p`
	if [[ "$pids" != "" ]]; then
		kill $pids
	fi
}

trap cleanup EXIT

for DIR in $PASSENGER_AUTOBUILDER_OUTPUT_DIR/*; do
	name=`basename "$DIR"`
	status "Syncing $DIR to Amazon S3..."
	if [[ "$name" =~ enterprise && "$S3_ENTERPRISE_NAME" != "" ]]; then
		name="$S3_ENTERPRISE_NAME"
	fi
	# s3cmd doesn't handle symlinks properly (it reuploads symlinked files even with --follow-symlinks),
	# so we have to use --skip-existing.
	chpst -l $PASSENGER_AUTOBUILDER_RUN_DIR/sync_to_s3.lock \
		s3cmd sync --follow-symlinks --skip-existing --delete-removed --acl-public \
		$DIR/by_release/ $S3_TARGET/$name/by_release/
done
